config/routes.rb
Rails.application.routes.draw do
  root 'requisitions#index'
  get    '/login',  to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'  

  resources :users do
    member do
      resources :profile
    end
  end

  resources :requisitions
  resources :personal_references, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personal_reference.rb
class PersonalReference < ApplicationRecord
  belongs_to :requisition

  validates_presence_of  :first_name, :second_name, :first_last_name, 
                        :second_last_name, :cell_phone_number

  def complete_name
    "#{self.first_name} #{self.second_name} #{self.first_last_name} #{self.second_last_name}"
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  def is_completed?
    self.attributes.each { |name, value| return false if value.blank? }
    true
  end
end

app/models/requisition.rb
class Requisition < ApplicationRecord
  belongs_to :user
  has_many :personal_references

  # validates_presence_of :income, :address_years, :company_years, :marital_status,
  #                       :requested_amount, :payment_terms, :bank, :comment, :company_name,
  #                       :company_phone_number, :dependents_number, :company_position, :has_sgmm,
  #                       :has_imss, :has_car

  validates_numericality_of :income, :requested_amount, greater_than: 1
  validates_numericality_of :address_years, :company_years, :dependents_number, only_intege: true

  accepts_nested_attributes_for :personal_references
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_many :requisitions

  def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def make_profile(auth)
    p = self.build_profile do |profile|
      profile.first_name = auth.info.first_name.split(' ').first
      profile.second_name = auth.info.first_name.split(' ').last
      profile.first_last_name = auth.info.last_name.split(' ').first
      profile.second_last_name = auth.info.last_name.split(' ').last
      profile.birth_date = Date.strptime(auth.extra.raw_info.birthday,'%m/%d/%Y') if auth.extra.raw_info.birthday?
      profile.gender = auth.extra.raw_info.gender
    end
    p.save
  end

  def has_profile?
    !self.profile.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :require_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to login_path unless current_user
  end

end

app/controllers/personal_references_controller.rb
class PersonalReferencesController < ApplicationController
  before_action :set_reference

  def show
  end

  private

  def set_reference
    @personal_reference = PersonalReference.find(params[:id])
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :require_user
  before_action :set_profile, only: [:edit, :update]

  def edit
  end

  def update
    @profile.update(profile_params)
    redirect_to root_path
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(
      :first_name, :second_name, :first_last_name, 
      :second_last_name, :birth_date, :curp, :rfc, 
      :gender, :birth_state, :phone_number
    )
  end
end

app/controllers/requisitions_controller.rb
class RequisitionsController < ApplicationController
  before_action :require_user
  before_action :set_requisition, only: [:edit, :update, :show]

  def index
    @requisitions = current_user.requisitions
  end

  def new
    @requisition = current_user.requisitions.new
  end

  def create
    @requisition = current_user.requisitions.new(requisition_params)
    head :unproccessable_entity unless @requisition.save
  end

  def show
  end

  def edit
    render 'new'
  end

  def update
    head :unproccessable_entity unless @requisition.update(requisition_params)
  end

  private
  def set_requisition
    @requisition = current_user.requisitions.find(params[:id])
  end

  def requisition_params
    params.require(:requisition)
    .permit(
      :income, :address_years, :company_years, :marital_status,
      :requested_amount, :payment_terms, :bank, :comment, :company_name,
      :company_phone_number, :dependents_number, :company_position, :has_sgmm,
      :has_imss, :has_car,
      personal_references_attributes: [ 
        :id, :first_name, :second_name, 
        :first_last_name, :second_last_name, :cell_phone_number
      ]
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      session[:user_id] = user.id
      current_user.make_profile(request.env["omniauth.auth"]) unless current_user.has_profile?
      redirect_to edit_profile_path(current_user.id)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ''
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
  def state_select_options
    [
      'AGUASCALIENTES',
      'BAJA CALIFORNIA NORTE',
      'BAJA CALIFORNIA SUR',
      'COAHUILA',
      'CHIHUAHUA',
      'COLIMA',
      'CAMPECHE',
      'CHIAPAS',
      'DISTRITO FEDERAL',
      'DURANGO',
      'GUERRERO',
      'GUANAJUATO',
      'HIDALGO',
      'JALISCO',
      'MICHOACAN',
      'MORELOS',
      'MEXICO',
      'NAYARIT',
      'NUEVO LEON',
      'OAXACA',
      'PUEBLA',
      'QUERETARO',
      'QUINTANA ROO',
      'SINALOA',
      'SAN LUIS POTOSI',
      'SONORA',
      'TAMAULIPAS',
      'TABASCO',
      'TLAXCALA',
      'VERACRUZ',
      'YUCATAN',
      'ZACATECAS'
    ]
  end

  def gender_select_options
    [['Masculino', 'male'], ['Femenino', 'female']]
  end
end

app/helpers/requisitions_helper.rb
module RequisitionsHelper
  def setup_requisition(requisition)
    3.times { requisition.personal_references.build } if requisition.id.nil?
    requisition
  end

  def has_select_options
    [['Si', 'true'], ['No', 'false']]
  end

  def marital_status_select_options
    ['Soltero/a', 'Casado/a', 'Viudo/a', 'Divorciado/a', 'Unión Libre', 'Comprometido/a']
  end

  def payment_terms_select_options
    [['6 meses', '6'],['12 meses', '12'], ['18 meses', '18'], ['24 meses', '24'], ['30 meses', '30'], ['36 meses', '36']]
  end

  def object_has(has_attr)
    if has_attr.instance_of? NilClass
      ''
    else 
      has_attr
    end
  end

  def bank_select_options
    [
      'Banco Nacional de México (Banamex)',
      'Banco Santander (México)',
      'HSBC México.',
      'Scotiabank Inverlat.',
      'BBVA Bancomer.',
      'Banco Mercantil del Norte (Banorte).',
      'Banco Interacciones.',
      'Banco Inbursa.',
      'banca Mifel.',
      'Banco Regional de Monterrey.',
      'Banco Invex.',
      'Banco del Bajio.',
      'Bansi.',
      'Banca Afirme.',
      'Bank of America México.',
      'Banco J.P. Morgan.',
      'Banco Ve Por Mas.',
      'American Express Bank (México).',
      'Investa Bank.',
      'CiBanco.',
      'Bank of Tokyo-Mitsubishi UFJ (México).',
      'Banco Monex.',
      'Deutsche Bank México.',
      'Banco Azteca.',
      'Banco Credit Suisse (México).',
      'Banco Autofin México.',
      'Barclays Bank México.',
      'Banco Ahorro Famsa.',
      'Intercam Banco.',
      'ABC Capital. ',
      'Banco Actinver.',
      'Banco Compartamos.',
      'Banco Multiva.',
      'UBS Bank México.',
      'Bancoppel.',
      'ConsuBanco.',
      'Banco Wal-Mart de México.',
      'Volkswagen Bank.',
      'Banco Base.',
      'Banco Pagatodo.',
      'Banco Forjadores.',
      'Bankaool.',
      'Banco Inmobiliario Mexicano.',
      'Fundación Dondé Banco.',
      'Banco Bancrea'
    ]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title AppCredit
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if current_user
      = render 'share/nav'
    .container
      = yield

app/views/personal_references/_show.html.haml
#dialog-show.modal.inmodal
  .modal-dialog
    .modal-content
      .modal-header
        %h4= @personal_reference.complete_name
      .modal-body
        %label Teléfono celular:
        = @personal_reference.cell_phone_number
      .modal-footer
        = link_to "Cerrar", "#", class: "btn btn-danger btn-cancel"

app/views/personal_references/show.js.erb
dialog_show = $("<%= j render 'show' %>").dialog({
  autoOpen: false,
  modal: true,
});

$('#dialog-show .btn-cancel').click(function(){
  dialog_show.dialog('close');
  return false;
});

dialog_show.dialog('open');

app/views/requisitions/_form.html.haml
#dialog-form.inmodal
  = form_for setup_requisition(@requisition), remote: true do |f|
    .modal-dialog
      .modal-content
        .modal-header
          %h4
        .modal-body
          #accordion.panel-group
            .panel.panel-default
              .panel-heading
                %h4.panel-title
                  %a.accordion-toggle{'data-parent': '#accordion', 'data-toggle': 'collapse', href: '#financial'}
                    Información Financiera
              #financial.panel-collapse.collapse.in
                .panel-body
                  = render 'requisitions/sections/financial', f: f
            .panel.panel-default
              .panel-heading
                %h4.panel-title
                  %a.accordion-toggle{'data-parent': '#accordion', 'data-toggle': 'collapse', href: '#job'}
                    Información Laboral
              #job.panel-collapse.collapse
                .panel-body
                  = render 'requisitions/sections/job', f: f
            .panel.panel-default
              .panel-heading
                %h4.panel-title
                  %a.accordion-toggle{'data-parent': '#accordion', 'data-toggle': 'collapse', href: '#personal'}
                    Información Personal
              #personal.panel-collapse.collapse
                .panel-body
                  = render 'requisitions/sections/personal', f: f
            .panel.panel-default
              .panel-heading
                %h4.panel-title
                  %a.accordion-toggle{'data-parent': '#accordion', 'data-toggle': 'collapse', href: '#personal_references'}
                    Referencias Personales
              #personal_references.panel-collapse.collapse
                .panel-body
                  = render 'requisitions/sections/personal_references', f: f
          .modal-footer
            %button{type:'submit', class: 'btn btn-success'} Guardar
            %button.btn.btn-default.btn-cancel.pull-left{'data-dismiss': 'modal', type: 'button'} Cerrar

app/views/requisitions/_requisition.html.haml
%tr[requisition]
  %td= requisition.requested_amount
  %td= requisition.income
  %td= requisition.bank
  %td= requisition.comment
  %td
    - requisition.personal_references.each do |reference|
      %li= link_to reference.complete_name, personal_reference_path(reference.id), remote: true, title: 'Ver Referencia Personal'
  %td
    = link_to edit_requisition_path(requisition), remote: true, title: 'Editar Solicitud' do
      %i.fa.fa-pencil
    = link_to requisition_path(requisition), remote: true, title: 'Ver Solicitud' do
      %i.fa.fa-file-text

app/views/requisitions/_show.html.haml
#dialog-show.modal.inmodal
  .modal-dialog
    .modal-content
      .modal-header
        %h4
          Monto Solicitado: $
          = @requisition.requested_amount
      .modal-body
        .row
          %h3 Información Financiera
          .col-xs-4
            =label(:requisition, :income)
            = @requisition.income
            %p
            =label(:requisition, :bank)
            = @requisition.bank
          .col-xs-5
            =label(:requisition, :payment_terms)
            = "#{@requisition.payment_terms} Meses"
            %p
            =label(:requisition, :comment)
            = @requisition.comment
        .row
          %h3 Información Laboral
          .col-xs-4
            =label(:requisition, :company_name)
            = @requisition.company_name
            %p
            =label(:requisition, :company_phone_number)
            = @requisition.company_phone_number
          .col-xs-5
            =label(:requisition, :company_position)
            = @requisition.company_position
            %p
            =label(:requisition, :company_years)
            = @requisition.company_years
        .row
          %h3 Información Personal
          .col-xs-4
            =label(:requisition, :address_years)
            = @requisition.address_years
            %p
            =label(:requisition, :marital_status)
            = @requisition.marital_status
            %p
            =label(:requisition, :dependents_number)
            = @requisition.dependents_number
          .col-xs-4
            =label(:requisition, :has_sgmm)
            = "#{@requisition.has_sgmm ? 'Si': 'No'}"
            %p
            =label(:requisition, :has_imss)
            = "#{@requisition.has_imss ? 'Si' : 'No'}"
            %p
            =label(:requisition, :has_car)
            = "#{@requisition.has_car ? 'Si' : 'No'}"
      .modal-footer
        = link_to 'Cerrar', "#", class: "btn btn-danger"

app/views/requisitions/create.js.erb
$("<%= j render @requisition %>")
.appendTo($('#requisitions'))
.effect('highlight', null, 2000);

app/views/requisitions/index.html.haml
.row
  .col-lg-12
    .margin-tb
      %h3
        Solicitudes de credito
      - if current_user.profile.is_completed?
        .pull-right
          = link_to new_requisition_path, remote: true, class: 'btn btn-success' do
            %i.fa.fa-plus
            Crear Solicitud
      - else
        %h4.pull-right
        %span.help-block.with-errors
          Completa tu perfil para poder realizar una solicitud.

    %table.table.table-hover#requisitions
      %thead
        %tr
          %th Monto Solicitado
          %th Ingreso
          %th Banco
          %th Comentarios
          %th Referencias
          %th Acciones
      %tbody
        = render @requisitions

app/views/requisitions/new.js.erb
// Dialog setup
dialog_form = $("<%= j render 'form' %>").dialog({
  autoOpen: false,
  width: 520,
  modal: true,
  close: function(){ dialog_form.dialog("destroy") },
});

$("#dialog-form .btn-cancel").click(function(){
  dialog_form.dialog("close");
  return false;
});

// Client side view update
$("#dialog-form form").on("ajax:success", function(e, xhr, status, error){
  dialog_form.dialog("close");
});

// Client side validation
$("#dialog-form form").on("ajax:before", function(e, xhr, status, error){
  f = $(e.currentTarget);

  // Validate Financial
  financial_attributes = ['requested_amount', 'payment_terms', 'income', 'bank', 'comment'];
  attributes_numbers = ['requested_amount', 'income', 'company_years', 'address_years', 'dependents_number']

  // Validate Numbers
  // for (i = 0; i < attributes_numbers.length; i++) {
  //   if(isNumber(attribute_value(attributes_numbers[i]))){
  //     $('#'+attributes_numbers[i]+'_error').html('Favor de introducir un número.');
  //     return false;
  //   }
  // }

  for (i = 0; i < financial_attributes.length; i++) {
    if(attribute_value(financial_attributes[i]) === ''){
      $('#'+financial_attributes[i]+'_error').html('Es obligatorio');
      return false;
    }
  }

  // Validate Job
  job_attributes = ['company_name', 'company_position', 'company_phone_number', 'company_years'];

  for (i = 0; i < job_attributes.length; i++) {
    if(attribute_value(job_attributes[i]) === ''){
      $('#'+job_attributes[i]+'_error').html('Es obligatorio');
      return false;
    }
  }

  // Validate Personal
  personal_attributes = ['address_years', 'marital_status', 'dependents_number', 'has_sgmm', 'has_imss', 'has_car'];
  for (i = 0; i < personal_attributes.length; i++) {
    if(attribute_value(personal_attributes[i]) === ''){
      $('#'+personal_attributes[i]+'_error').html('Es obligatorio');
      return false;
    }
  }

  // Validate Personal References
  personal_references = ['first_name', 'second_name', 'first_last_name', 'second_last_name', 'cell_phone_number'];
    for (i = 0; i < personal_references.length; i++) {
      if(attribute_value_personal_reference(personal_references[i]) === ''){
        $('#'+personal_references[i]+'_error').html('Es obligatorio');
        return false;
      }
    }

    for (i = 0; i < personal_references.length; i++) {
      if(attribute_value_personal_reference_1(personal_references[i]) === ''){
      $('#'+personal_references[i]+'_error').html('Es obligatorio');
      return false;
      }
    }

    for (i = 0; i < personal_references.length; i++) {
      if(attribute_value_personal_reference_2(personal_references[i]) === ''){
      $('#'+personal_references[i]+'_error').html('Es obligatorio');
      return false;
    }
}

});

// Client side error handling
$("#dialog-form form").on("ajax:error", function(e, xhr, status, error){
  alert("Error al registrar datos");
});

// Finally, open the dialog
dialog_form.dialog("open");



function attribute_value(attribute){
 return f.find('#requisition_'+attribute).val();
}

// Validate Number

// function isNumber(n) {
//   return !isNaN(parseFloat(n)) && isFinite(n);
// }

// to PersonalReferences
function attribute_value_personal_reference(attribute){
  return f.find('#requisition_personal_references_attributes_0_'+attribute).val();
}

// to PersonalReferences
function attribute_value_personal_reference_1(attribute){
  return f.find('#requisition_personal_references_attributes_1_'+attribute).val();
}

// to PersonalReferences
function attribute_value_personal_reference_2(attribute){
  return f.find('#requisition_personal_references_attributes_2_'+attribute).val();
}

app/views/requisitions/sections/_financial.html.haml
.row
  .col-xs-5
    .form-group
      = f.label :requested_amount
      = f.number_field :requested_amount, class: "form-control", placeholder: 'Desde 5,000', step: '1', min: 5_000
      %span.help-block.with-errors#requested_amount_error
    .form-group
      = f.label :payment_terms
      = f.select(:payment_terms, options_for_select(payment_terms_select_options, f.object.payment_terms || ''),{prompt: 'Seleccionar'}, { 'data-width': "100%", class: "form-control"})
      %span.help-block.with-errors#payment_terms_error
    .form-group
      = f.label :income
      = f.number_field :income, class: "form-control", placeholder: "Ingreso", step: '0.1', min: 1
      %span.help-block.with-errors#income_error
  .col-xs-5
    .form-group
      = f.label :bank
      = f.select(:bank, options_for_select(bank_select_options, f.object.bank || ''),{prompt: 'Seleccionar'}, { 'data-width': '100%', class: 'form-control'})
      %span.help-block.with-errors#bank_error
    .form-group
      = f.label :comment
      = f.text_area :comment, class: "form-control", placeholder: "Comentario..."
      %span.help-block.with-errors#comment_error

app/views/requisitions/sections/_job.html.haml
.row
  .col-xs-5
    .form-group
      = f.label :company_name
      = f.text_field :company_name, class: "form-control", placeholder: "Nombre de empresa"
      %span.help-block.with-errors#company_name_error
    .form-group
      = f.label :company_position
      = f.text_field :company_position, class: "form-control", placeholder: "Posición en la empresa"
      %span.help-block.with-errors#company_position_error
  .col-xs-5
    .form-group
      = f.label :company_phone_number
      = f.text_field :company_phone_number, class: "form-control", placeholder: "Núm. de tel. de la empresa"
      %span.help-block.with-errors#company_phone_number_error
    .form-group
      = f.label :company_years
      = f.number_field :company_years, class: "form-control", placeholder: "Años en la empresa", min: 1
      %span.help-block.with-errors#company_years_error

app/views/requisitions/sections/_personal.html.haml
.row
  .col-xs-6
    .form-group
      = f.label :address_years
      = f.number_field :address_years, class: "form-control", placeholder: "Años viviendo en la dirección", min: 1
      %span.help-block.with-errors#address_years_error
    .form-group
      = f.label :marital_status
      = f.select(:marital_status, options_for_select(marital_status_select_options, f.object.marital_status || ''),{prompt: 'Seleccionar'}, { 'data-width': '100%', class: 'form-control'})
      %span.help-block.with-errors#marital_status_error
    .form-group
      = f.label :dependents_number
      = f.number_field :dependents_number, class: "form-control", placeholder: "Número de dependientes", min: 0
      %span.help-block.with-errors#dependents_number_error
  .col-xs-4
    .form-group
      = f.label :has_sgmm
      = f.select(:has_sgmm, options_for_select(has_select_options, object_has(f.object.has_sgmm)),{prompt: 'Seleccionar'}, { 'data-width': '100%', class: 'form-control'})
      %span.help-block.with-errors#has_sgmm_error
    .form-group
      = f.label :has_imss
      = f.select(:has_imss, options_for_select(has_select_options, object_has(f.object.has_imss)),{prompt: 'Seleccionar'}, { 'data-width': '100%', class: 'form-control'})
      %span.help-block.with-errors#has_imss_error
    .form-group
      = f.label :has_car
      = f.select(:has_car, options_for_select(has_select_options, object_has(f.object.has_car)),{prompt: 'Seleccionar'}, { 'data-width': '100%', class: 'form-control'})
      %span.help-block.with-errors#has_car_error

app/views/requisitions/sections/_personal_references.html.haml
.row
  = f.fields_for :personal_references do |ff|
    .col-xs-4
      %h6 Referencia Personal:
      %span.help-block.with-errors#personal_reference_error
      .form-group
        = ff.label :first_name
        = ff.text_field :first_name, class: "form-control", placeholder: 'Primer Nombre'
        %span.help-block.with-errors#first_name_error
      .form-group
        = ff.label :second_name
        = ff.text_field :second_name, class: "form-control", placeholder: 'Segundo Nombre'
        %span.help-block.with-errors#second_name_error
      .form-group
        = ff.label :first_last_name
        = ff.text_field :first_last_name, class: "form-control", placeholder: 'Primer Apellido'
        %span.help-block.with-errors#first_last_name_error
      .form-group
        = ff.label :second_last_name
        = ff.text_field :second_last_name, class: "form-control", placeholder: 'Segundo Apellido'
        %span.help-block.with-errors#second_last_name_error
      .form-group
        = ff.label :cell_phone_number
        = ff.text_field :cell_phone_number, class: "form-control", placeholder: 'Núm. Celular'
        %span.help-block.with-errors#cell_phone_number_error

app/views/requisitions/show.js.erb
dialog_show = $("<%= j render 'show' %>").dialog({
  autoOpen: false,
  modal: true,
});

$('#dialog-show .btn-cancel').click(function(){
  dialog_show.dialog('close');
  return false;
});

dialog_show.dialog('open');

app/views/requisitions/update.js.erb
$("<%= j render @requisition %>")
.replaceAll("#requisition_<%= @requisition.id %>")
.effect('highlight', null, 2000);

app/views/share/_nav.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'App-Credit', '#', class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: active_class(requisitions_path)}
          = link_to requisitions_path do
            Solicitudes de credito
            %span.sr-only (current)
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown{:role => "presentation"}
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Bienvenido
            = succeed "!" do
              %strong= current_user.name
            %span.caret
          %ul.dropdown-menu
            %li{class: active_class(edit_profile_path(current_user.id))}
              = link_to edit_profile_path(current_user.id) do
                Perfil
                %span.sr-only (current)
            %li
              = link_to "Cerrar Sesión", signout_path, id: "sign_out"